#!/usr/bin/env groovy

node {
   stage('checkout') {
       checkout scm
   }
   
   stage('Installing Packages') {
      sh "java -version"
   }

   stage('packaging') {
       sh "mvn -U clean package -DskipTests"
   }

   def gupshupsmssendVersion
   stage ('create Image Version'){
   gupshupsmssendVersion = sh (
   script: "date +'%Y-%m-%d-%H.%M'",
   returnStdout: true,
      )
   }

   def dockerImage
   stage('build docker') {
       sh "cp -R docker target/"
       sh "cp target/*.jar target/docker/"
       dockerImage = docker.build('telemed/gupshupsmssend', 'target/docker')
   }

   stage('publish docker') {
       docker.withRegistry('http://172.16.11.166:37719', 'telemed') {
           dockerImage.push "${gupshupsmssendVersion}"
         }
      }

   stage('delete docker Image') {
       sh "docker rmi telemed/gupshupsmssend"
       sh "docker rmi 172.16.11.166:37719/telemed/gupshupsmssend:${gupshupsmssendVersion}"
       }   

   stage('Deploy on Dev Env') {
         sshagent (credentials: ['nsdl']) {
       sh "echo 'gupshupsmssendVersion=${gupshupsmssendVersion}' > .env"
       sh "scp -o StrictHostKeyChecking=no .env mosip@172.30.151.100:/var/workspace/telemedicine"
       sh "ssh -o StrictHostKeyChecking=no -l mosip 172.30.151.100 /var/workspace/telemedicine/helper/gupshupsmssend.sh"
         }
       }  
       
   }
  
