#!/usr/bin/env groovy

node {
   stage('checkout') {
       checkout scm
   }
   
   stage('Installing Packages') {
      sh "java -version"
   }

   stage('packaging') {
       sh "mvn -U clean package -DskipTests"
   }

  // stage('Unit Test') {
  //     sh "mvn test"
  // }

   def paydemoVersion
   stage ('create Image Version'){
   paydemoVersion = sh (
   script: "date +'%Y-%m-%d-%H.%M'",
   returnStdout: true,
      )
   }

   def dockerImage
   stage('build docker') {
       sh "cp -R docker target/"
       sh "cp target/*.jar target/docker/"
       dockerImage = docker.build('telemed/paydemoservice', 'target/docker')
   }

   stage('publish docker') {
       docker.withRegistry('http://172.16.11.166:37719', 'telemed') {
           dockerImage.push "${paydemoVersion}"
         }
      }
      
   stage('delete docker Image') {
       sh "docker rmi telemed/paydemoservice"
       sh "docker rmi 172.16.11.166:37719/telemed/paydemoservice:${paydemoVersion}"
       }

   stage('Deploy on Dev Env.') {
         sshagent (credentials: ['nsdl']) {
       sh "echo 'paydemoVersion=${paydemoVersion}' > .env"
       sh "scp -o StrictHostKeyChecking=no .env mosip@172.16.11.167:/var/workspace/telemedicine"
       sh "ssh -o StrictHostKeyChecking=no -l mosip 172.16.11.167 /var/workspace/telemedicine/helper/paydemoservice.sh"
         }
       }              
       
   }

